# Binance P2P Alert Configuration

# Trading pair configuration
asset: "USDT"
fiat: "VND"

# Alert conditions
max_price: 26_200.0
min_of_max_amount: 5_000_000.0
min_rating: 95

# API configuration
page_size: 20

enable_slack_alert: true
